sudo: true

language: node_js

node_js:
  - 8.4

cache:
  directories:
    - node_modules

before_install:
- npm i -g github-release-from-changelog

script:
  - yarn build

deploy:
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    github_token: $GITHUB_TOKEN
    script: github-release-from-changelog
    skip_cleanup: true
    on:
      tag: true
