sudo: true

language: node_js

node_js:
  - "lts"

cache:
  directories:
    - node_modules

before_install:
  - npm i -g github-release-from-changelog

script:
  - yarn build:example

deploy:
  - provider: npm
    name: NPM
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: example/build
    on:
      branch: master
  - provider: script
    github_token: $GITHUB_TOKEN
    script: github-release-from-changelog
    skip_cleanup: true
    on:
      tags: true
